### ISSUE TITLE
Ad support for 3x devices

### ISSUE THREAD

**Issue by LeoNatan** [alexruperez/ARSpeechActivity#4]
Hi,

Please add support for 3x devices.

Thanks

**Comment by alexruperez** [comment]
Done! :+1: Thanks! https://github.com/alexruperez/ARSpeechActivity/commit/deaa92617f2945871b6b651f3afdb13b0137b110

**Comment by LeoNatan** [comment]
Nice, thanks!

**Comment by alexruperez** [comment]
@LeoNatan, if you use it with CocoaPods, use the 0.1.1 version.
